<?php
/**
* The Evolution Framework
*
* WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
* Please do all modifications in the form of a child theme.
*
* This file loads all the scripts and styles
*
* @package Evolution\Functions\
* @author  Andreas Hecht
* @license GPL-2.0+
* @link    https://andreas-hecht.com/wordpress-themes/evolution
*/


if ( !function_exists( 'evolution_scripts' ) ) :
/**
 * Enqueue scripts and styles.
 */
function evolution_scripts() { 

    wp_enqueue_style( 'evolution-style', get_stylesheet_uri() );
    
    wp_enqueue_style( 'fontawesome', get_theme_file_uri( '/css/font-awesome.min.css' ), array( 'evolution-style' ), '1.0.0' );

    wp_enqueue_script( 'evolution-navigation', get_template_directory_uri() . '/js/navigation.js', array(), '20160525', true );

    if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
        wp_enqueue_script( 'comment-reply' );
    }
}
add_action( 'wp_enqueue_scripts', 'evolution_scripts' );
endif;





if ( !function_exists( 'evolution_register_woostyles' ) ) :
/**
 * Register and load Custom Evolution WooCommerce Styles only on the right pages
 */
function evolution_woostyles() { 

    wp_register_style( 'evolution-woostyles', get_template_directory_uri() . '/inc/woocommerce/css/woo-styles.min.css' );

    if ( function_exists( 'is_woocommerce' ) ) :
    wp_enqueue_style( 'evolution-woostyles' ); 
    endif;
}
add_action( 'wp_enqueue_scripts', 'evolution_woostyles' );
endif;