<?php
/**
 * The Evolution Framework.
 * 
 * Template: 404.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution
 */

get_header();

/**
 * Functions hooked in to 'evolution_do_404' action
 * 
 * @see /inc/structure/evolution-loops.php
 * @see /inc/structure/evolution-hooks.php
 * 
 * @hooked  evolution_top_markup - 5
 * @hooked evolution_404_content - 15
 * @hooked  evolution_bottom_markup - 30
 */
do_action( 'evolution_do_404' );


get_footer(); 
