<?php
/**
 * The Evolution Framework.
 * 
 * Template: archive.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */

get_header();

/**
 * Functions hooked in the 'evolution_do_archive' action
 * 
 * @see /inc/structure/evolution-loops.php
 * @see /inc/structure/evolution-hooks.php
 * @see /inc/structure/evolution-loop-content.php
 *
 * @hooked  evolution_top_markup() - 5
 * @hooked evolution_do_archive_loop() - 10
 * @hooked  evolution_bottom_markup() - 30
 */
do_action( 'evolution_do_archive' );

get_sidebar();

get_footer();
