<?php
/**
 * The Evolution Framework.
 * 
 * Template: footer.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @see /inc/structure/markup/evolution-footer.php
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */

/**
 * Functions hooked in to 'evolution_do_footer' action
 * 
 * @see /inc/structure/markup/evolution-footer.php
 * 
 * @hooked  evolution_footer_top_markup - 5
 * @hooked  evolution_site_info - 10
 * @hooked  evolution_site_credit - 15
 * @hooked  evolution_footer_bottom_markup - 20
 */
do_action( 'evolution_do_footer' );
