<?php
/**
* The Evolution Framework
*
* WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
* Please do all modifications in the form of a child theme.
*
* This file loads all parts of the Evolution Framework
*
* @package Evolution
* @author  Andreas Hecht
* @license GPL-2.0+
* @link    https://andreas-hecht.com/wordpress-themes/evolution
*/

/**
 * Inits the Evolution Framework
 */
require get_template_directory() . '/inc/init-evolution.php';
