<?php
/**
* The Evolution Framework
*
* WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
* Please do all modifications in the form of a child theme.
*
* Init Evolution Framework
*
* @package Evolution\Functions\
* @author  Andreas Hecht
* @license GPL-2.0+
* @link    https://andreas-hecht.com/wordpress-themes/evolution
*/


/**
 * Init Evolution Framework
 * Without these line of code, evolution do not work!
 */ 
require_once( get_template_directory() . '/inc/init-evolution.php');



/**
 * Automatic Theme Updater
 */ 
require_once('wp-updates-theme.php');
new WPUpdatesThemeUpdater_2149( 'http://wp-updates.com/api/2/theme', basename( get_template_directory() ) );
