<?php
/**
 * The Evolution Framework.
 * 
 * Template: index.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @see /inc/structure/evolution-loops.php
 * @see /inc/structure/evolution-hooks.php
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution
 */

get_header();

// This hook is free for your actions
do_action( 'evolution_before_main' );

/**
 * Functions hooked in to 'evolution_do_main' action
 * 
 * @see /inc/structure/evolution-loops.php
 * @see /inc/structure/evolution-hooks.php
 * 
 * @hooked  evolution_top_markup - 5
 * @hooked  evolution_before_main_loop
 * @hooked evolution_do_main_loop - 10
 * @hooked  evolution_after_main_loop
 * @hooked  evolution_bottom_markup - 30
 */
do_action( 'evolution_do_main' );

get_sidebar();

get_footer();
