<?php
/**
 * The Evolution Framework.
 * 
 * Template: sidebar-woocommerce.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution
 */

echo '<div id="secondary" class="sidebar-area" role="complementary">', "\n", '<div class="normal-sidebar widget-area">';

    if ( is_active_sidebar( 'woocommerce' ) ) :

    do_action( 'evolution_before_woo_sidebar' );

    dynamic_sidebar( 'woocommerce' );

    do_action( 'evolution_after_woo_sidebar' );

endif;

echo '</div><!-- .normal-sidebar -->', "\n", '</div><!-- #secondary -->';