<?php
/**
 * The Evolution Framework.
 * 
 * Template: sidebar.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @see /inc/structure/evolution-sidebar.php
 *
 * @package Evolution\Templates\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */
if (   ! is_active_sidebar( 'sidebar' ) ) {
    return;
}
/**
 * Functions hooked in the 'evolution_do_main_sidebar' action
 * 
 * @return main widget area
 * 
 * @see /inc/structure/markup/evolution-sidebars.php
 * 
 * @hooked evolution_before_main_sidebar
 * @hooked  evolution_main_sidebar() - 10
 * @hooked evolution_after_main_sidebar
 */
do_action( 'evolution_do_main_sidebar' );
