<?php
/**
 * The Evolution Framework.
 * 
 * Content of footer.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @hooked evolution_do_footer()
 * 
 * @see footer.php
 *
 * @package Evolution\Markup\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */


add_action( 'evolution_do_footer', 'evolution_footer_top_markup', 5 );
add_action( 'evolution_do_footer', 'evolution_site_info', 10 );
add_action( 'evolution_do_footer', 'evolution_site_credit', 15 );
add_action( 'evolution_do_footer', 'evolution_footer_bottom_markup', 20 );



if ( ! function_exists( 'evolution_footer_top_markup' ) ) :
/**
 * Outputs the opening markup for footer content and get widget areas
 * 
 * @hooked evolution_do_footer() - 5
 * 
 * @since 1.0.0
 */
function evolution_footer_top_markup() {

    echo '</div><!-- #content -->', "\n", '<footer id="colophon" class="site-footer">';

    get_sidebar( 'footer' ); 

    echo '<div class="site-bottom">';
}
endif;




if ( ! function_exists( 'evolution_site_info' ) ) :
/**
 * Outputs the year, the copyright and the site name
 * 
 * @hooked evolution_do_footer() - 10
 * 
 * @since 1.0.0
 */
function evolution_site_info() {

    echo '<div class="site-info">', "\n", '<div class="site-copyright">';
    
    echo '&copy;&nbsp;'; echo date( 'Y' ); 
?> 
    <a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">
    <?php bloginfo( 'name' ); ?></a> 
    <?php echo get_theme_mod( 'evolution_footer_text' );
    
    echo '</div><!-- .site-copyright -->';
}
endif;    
 


if ( ! function_exists( 'evolution_site_credit' ) ) :
/**
 * Outputs powered by WordPress and the theme credit link to our website
 * 
 * @hooked evolution_do_footer() - 15
 * 
 * @since 1.0.0
 */
function evolution_site_credit() {
    
       if ( get_theme_mod( 'evolution_footer_hide' ) == '0' ) : 

        echo '<div class="site-credit">';
        printf( wp_kses( __( 'Powered by <a href="%1$s">%2$s</a>', 'evolution' ), 
        array( 'a' => array( 'href' => array() ) ) ), esc_url( __( 'https://wordpress.org/', 'evolution' ) ), 'WordPress' );
        echo  '<span class="site-credit-sep"> | </span>';
        printf( wp_kses( __( 'Theme: <a href="%1$s">Evolution</a> by %3$s', 'evolution' ), 
        array( 'a' => array( 'href' => array() ) ) ), esc_url( __( 'https://andreas-hecht.com/wordpress-themes/evolution/', 'evolution' ) ), 'evolution', 'Andreas Hecht' );
        endif;
}
endif;




if ( ! function_exists( 'evolution_footer_bottom_markup' ) ) :
/**
 * Outputs the closing footer markup and the wp_footer() action hook
 * 
 * @hooked evolution_do_footer() - 20
 * 
 * @since 1.0.0
 */
function evolution_footer_bottom_markup() {
        
    echo '</div><!-- .site-credit -->', "\n", '</div><!-- .site-info -->', "\n", '</div><!-- .site-bottom -->';
    echo '</footer><!-- #colophon -->', "\n", '</div><!-- #page -->';
    wp_footer();
    echo '</body>', "\n", '</html>';
}
endif;