<?php
/**
 * The Evolution Framework.
 * 
 * Content of header.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @hooked evolution_do_meta()
 * @hooked evolution_do_header()
 * 
 * @see header.php
 *
 * @package Evolution\Structure\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution
 */

add_action( 'evolution_do_meta', 'evolution_meta', 10 );

add_action( 'evolution_do_header', 'evolution_header_top_markup', 5 );
add_action( 'evolution_do_header', 'evolution_branding', 10 );
add_action( 'evolution_do_header', 'evolution_navigation', 20 );
add_action( 'evolution_do_header', 'evolution_header_image', 30 );
add_action( 'evolution_do_header', 'evolution_header_bottom_markup', 50 );



if ( ! function_exists( 'evolution_meta' ) ) :
/**
 * Outputs the meta markup for the header
 * 
 * @hooked evolution_do_meta() - 5
 * 
 * @since 1.0.0
 */
function evolution_meta() {
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
    <head>
        <meta charset="<?php bloginfo( 'charset' ); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
        <?php wp_head(); ?>
    </head> 
<?php }
endif;




if ( ! function_exists( 'evolution_header_top_markup' ) ) :
/**
 * Outputs the first markup after header
 * 
 * @hooked evolution_header() - 5
 * 
 * @since 1.0.0
 */
function evolution_header_top_markup() {
 ?>
<body <?php body_class(); ?>>
    
<?php echo '<div id="page" class="hfeed site">', "\n", '<a class="skip-link screen-reader-text" href="#content">';
  
   esc_html_e( 'Skip to content', 'evolution' );
    
    echo '</a>', "\n", '<header id="masthead" class="site-header">';
}
endif;




if ( ! function_exists( 'evolution_branding' ) ) :
/**
 * Outputs the logo, the site title / description and the header widget area
 * 
 * @hooked evolution_header() - 10
 * 
 * @since 1.0.0
 */
function evolution_branding() {

    echo '<div class="site-branding">', "\n", '<div class="evo-one-half">';
    
    evolution_logo();
                               
    evolution_site_title();
                               
    if ( ! get_theme_mod( 'evolution_hide_blogdescription' ) ) :
                               
        echo '<div class="site-description">';
                               
        bloginfo( 'description' );
                               
        echo '</div>';
                               
        endif;
    
        echo '</div><!-- .evo-one-half -->', "\n", '<div class="evo-one-half evo-column-last">', "\n", '<div class="header-widget-area">';
    
        dynamic_sidebar( 'header-right' );
                               
    echo '</div><!-- .header-widget-area -->', "\n", '</div><!-- .evo-one-half.evo-column-last -->', "\n", '</div><!-- .site-branding -->';
}
endif;




if ( ! function_exists( 'evolution_navigation' ) ) :
/**
 * Outputs main navigation with search form
 * 
 * @hooked evolution_header() - 20
 * 
 * @since 1.0.0
 */
function evolution_navigation() {

if ( ! get_theme_mod( 'evolution_hide_navigation' ) ) :
    
    echo '<div class="clear"></div>', "\n", '<nav id="site-navigation" class="main-navigation">', "\n", '<button class="menu-toggle"><span class="menu-text">';
    
    esc_html_e( 'Menu', 'evolution' );
    
    echo '</span></button>';

    wp_nav_menu( array( 'theme_location' => 'primary' ) );
                                 
    if ( ! get_theme_mod( 'evolution_hide_search' ) ) :
                                 
    get_search_form();
                                 
    endif;
    echo '</nav><!-- #site-navigation -->';
    endif;   
}
endif;




if ( ! function_exists( 'evolution_header_image' ) ) :
/**
 * Outputs image below header, if needed
 * 
 * @hooked evolution_header() - 30
 * 
 * @since 1.0.0
 */
function evolution_header_image() {
    
if ( is_page() && has_post_thumbnail() ) :
    
    echo '<div id="header-image" class="header-image">', "\n", '<figure>';
    
    the_post_thumbnail( 'evolution-page' );
    
    echo '</figure>', "\n", '</div><!-- #header-image -->';

    elseif ( ( get_header_image() && 'site' == get_theme_mod( 'evolution_header_display' ) ) ||
              ( get_header_image() && 'page' == get_theme_mod( 'evolution_header_display' ) && is_page() ) ||
              ( get_header_image() && 'page' != get_theme_mod( 'evolution_header_display' ) && is_home() ) ) :
    
    echo '<div id="header-image" class="header-image">', "\n", '<figure>'; ?>
    
    <img src="'<?php header_image(); ?>" width="<?php echo get_custom_header()->width; ?>" height="<?php echo get_custom_header()->height; ?>" alt="Header Image" />

    <?php echo '</figure>', "\n", '</div><!-- #header-image -->';
    
endif;
}
endif;




if ( ! function_exists( 'evolution_header_bottom_markup' ) ) :
/**
 * Outputs the closing header markup and the opening content markup
 * 
 * @hooked evolution_header() - 50
 * 
 * @since 1.0.0
 */
function evolution_header_bottom_markup() {

    echo '</header><!-- #masthead -->', "\n", '<div id="content" class="site-content">';    
}
endif;
