<?php
/**
 * The Evolution Framework.
 * 
 * Content of sidebar.php
 *
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * @see sidebar.php
 * @see sidebar-footer.php
 * @see sidebar-woocommerce.php
 *
 * @package Evolution\Structure\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */

add_action( 'evolution_do_main_sidebar', 'evolution_main_sidebar'  );
add_action( 'evolution_do_footer_sidebar', 'evolution_footer_sidebar' );




if ( ! function_exists( 'evolution_main_sidebar' ) ) :
/**
 * Outputs the content for the main sidebar area
 * 
 * @hooked evolution_do_main_sidebar() - 10
 * 
 * @see sidebar.php
 * 
 * @since 1.0.0
 */
function evolution_main_sidebar() {
    
echo '<div id="secondary" class="sidebar-area" role="complementary">',"\n", '<div class="normal-sidebar widget-area">';

if ( is_active_sidebar( 'sidebar' ) ) :

    do_action( 'evolution_before_main_sidebar' ); 

    dynamic_sidebar( 'sidebar' );

    do_action( 'evolution_after_main_sidebar' );

endif;

echo '</div><!-- .normal-sidebar -->', "\n", '</div><!-- #secondary -->';
}
endif;




if ( ! function_exists( 'evolution_footer_sidebar' ) ) :
/**
 * Outputs the content for the footer widget areas
 * 
 * @hooked evolution_do_footer_sidebar() - 10
 * 
 * @see sidebar-footer.php
 * 
 * @since 1.0.0
 */
function evolution_footer_sidebar() {
    
if ( is_active_sidebar( 'footer-1' ) || is_active_sidebar( 'footer-2' ) || is_active_sidebar( 'footer-3' ) || is_active_sidebar( 'footer-4' ) ) : 

    echo '<div id="supplementary" class="footer-widget-area" role="complementary">', "\n", '<div class="footer-widget-wrapper">', "\n", '<div class="footer-widget">';
    
            if ( is_active_sidebar( 'footer-1' ) ) : 
            echo '<div class="footer-1 footer-widget widget-area">';
            dynamic_sidebar( 'footer-1' );
            echo '</div><!-- .footer-widget-1 -->';
            endif;
            if ( is_active_sidebar( 'footer-2' ) ) : 
            echo '<div class="footer-2 footer-widget widget-area">';
            dynamic_sidebar( 'footer-2' );
            echo '</div><!-- .footer-widget-2 -->';
            endif;
            if ( is_active_sidebar( 'footer-3' ) ) :
            echo '<div class="footer-3 footer-widget widget-area">';
            dynamic_sidebar( 'footer-3' );
            echo '</div><!-- .footer-widget-3 -->';
            endif;
            if ( is_active_sidebar( 'footer-4' ) ) :
            echo '<div class="footer-4 footer-widget widget-area">';
            dynamic_sidebar( 'footer-4' );
            echo '</div><!-- .footer-widget-4 -->';
            endif;
    echo '</div><!-- .footer-widget -->', "\n", '</div><!-- .footer-widget-wrapper -->', "\n", '</div><!-- #supplementary -->';
    endif;
}
endif;
