<?php
/**
 * The Evolution Framework.
 * 
 * Jetpack Compatibility File
 * See: http://jetpack.me/
 * 
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Evolution\Compatibility\
 * @author  Andreas Hecht
 * @license GPL-2.0+
 * @link https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
 */


if ( ! function_exists( 'evolution_jetpack_setup' ) ) :
/**
 * Add theme support for Infinite Scroll.
 */
function evolution_jetpack_setup() {
    
	add_theme_support( 'infinite-scroll', array(
		'container' => 'main',
		'type'      => 'click',
		'render'    => 'evolution_infinite_scroll_render',
		'footer'    => false,
	) );
}
add_action( 'after_setup_theme', 'evolution_jetpack_setup' );
endif;




if ( ! function_exists( 'evolution_infinite_scroll_render' ) ) :
/**
 * The Loop for rendering the inifinite scroll action
 */
function evolution_infinite_scroll_render() {
    
	while ( have_posts() ) : the_post();
    
		if ( is_archive() || is_search() ) {
            
            evolution_list_content();
            
		} else {
            
        evolution_summary_content();
            
        }
	endwhile;
}
endif;




if ( ! function_exists( 'evolution_remove_related_posts' ) ) :
/**
 * Change headline of Related Posts
 */
function evolution_remove_related_posts() {
    
    if ( class_exists( 'Jetpack_RelatedPosts' ) ) {
        
        $jprp = Jetpack_RelatedPosts::init();
        
        $callback = array( $jprp, 'filter_add_target_to_dom' );
        
        remove_filter( 'the_content', $callback, 40 );
    }
}
add_filter( 'wp', 'evolution_remove_related_posts', 20 );
endif;




if ( ! function_exists( 'evolution_related_posts_headline' ) ) :
/**
 * headline of Related Posts
 * 
 * @return headline
 */
function evolution_related_posts_headline( $headline ) {
    
	$headline = sprintf(
				'<h2 class="jp-relatedposts-title">%s</h2>',
				esc_html__( 'You might also like', 'evolution' )
				);
    
	return $headline;
}
add_filter( 'jetpack_relatedposts_filter_headline', 'evolution_related_posts_headline' );
endif;