<?php
/**
 * The Evolution Framework
 * 
 * WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * Main hooks file for loops and content parts loaded inside the loops
 * 
 * @see /inc/structur/evolution-loops.php
 * @see /inc/frontend/evolution-loop-content.php
 * @see template files
 * 
 * @package Evolution Framework\structure\
 * 
 */ 

/* ================================================
#       1 - MARKUP INIT - OPENING MARKUP
================================================ */

/**
 * Markup above loop
 *
 * @see  evolution_top_markup()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_main', 'evolution_top_markup', 5 );
add_action( 'evolution_do_page', 'evolution_top_markup', 5 );
add_action( 'evolution_do_single', 'evolution_top_markup', 5 );
add_action( 'evolution_do_archive', 'evolution_top_markup', 5 );
add_action( 'evolution_do_search', 'evolution_top_markup', 5 );
add_action( 'evolution_do_404', 'evolution_top_markup', 5 );


/* ================================================
#       2 - MARKUP INIT - CLOSING MARKUP
================================================ */

/**
 * Markup below loop
 *
 * @see  evolution_bottom_markup()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_main', 'evolution_bottom_markup', 30 );
add_action( 'evolution_do_page', 'evolution_bottom_markup', 30 );
add_action( 'evolution_do_single', 'evolution_bottom_markup', 30 );
add_action( 'evolution_do_archive', 'evolution_bottom_markup', 30 );
add_action( 'evolution_do_search', 'evolution_bottom_markup', 30 );
add_action( 'evolution_do_404', 'evolution_bottom_markup', 30 );


/* ================================================
#       3 - LOOPS INIT
================================================ */

/**
 * Loop for pages on page.php
 *
 * @see  evolution_do_page_loop()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_page', 'evolution_do_page_loop', 10 );



/**
 * Loop for main content on index.php
 *
 * @see  evolution_do_main_loop()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_main', 'evolution_do_main_loop', 10 );



/**
 * Loop for main content on single.php
 *
 * @see  evolution_do_single_loop()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_single', 'evolution_do_single_loop', 10 );



/**
 * Loop for the archive content on archive.php
 *
 * @see  evolution_do_archive_loop()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_archive', 'evolution_do_archive_loop', 10 );



/**
 * Loop for the archive content on search.php
 *
 * @see  evolution_do_search_loop()
 * 
 * @since 1.0.0
 */
add_action( 'evolution_do_search', 'evolution_do_search_loop', 10 );



/* ================================================
#       4 - LOADING CONTENT PARTS INSIDE THE LOOPS
================================================ */

/**
 * Loads content parts for the main loop
 * 
 * @return full content
 *
 * @see  /inc/structure/evolution-loops.php
 * @see  /inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */
add_action( 'loop_full_content', 'evolution_full_content' );

/**
 * Loads content parts for the main loop
 * 
 * @return excerpt content
 *
 * @see  /inc/structure/evolution-loops.php
 * @see  /inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */
add_action( 'loop_summary_content', 'evolution_summary_content' );

/**
 * Loads content parts for the pages / standard template
 * 
 * @return page content
 *
 * @see  /inc/structure/evolution-loops.php
 * @see  /inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */
add_action( 'loop_page_content', 'evolution_page_content' );

/**
 * Loads content parts for single content
 * 
 * @return single content
 *
 * @see  /inc/structure/evolution-loops.php
 * @see  /inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */
add_action( 'loop_single_content', 'evolution_single_content' );

/**
 * Loads content parts for search content
 * 
 * @return search content
 *
 * @see  /inc/structure/evolution-loops.php
 * @see  /inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */
add_action( 'loop_search_content', 'evolution_list_content' );



/* ================================================
#       5 - LOADING CONTENT PARTS INSIDE THE LOOPS
================================================ */


/**
 * Load share buttons
 * 
 * @see evolution_share_buttons()
 * @see inc/frontend/evolution-frontend-functions.php
 * 
 * @since 1.0.0
 */ 
if (get_theme_mod("share-buttons") == 'checked') : 
add_action( 'evolution_after_thumbnail', 'evolution_share_buttons', 10 );
endif;




/**
 * Load Author bio box
 * 
 * @see evolution_author_profile()
 * @see inc/frontend/evolution-frontend-functions.php
 * 
 * @since 1.0.0
 */ 
add_action( 'evolution_after_content', 'evolution_author_profile' );



/**
 * Show the category for posts
 * 
 * @see evolution_category()
 * @see inc/frontend/evolution-frontend-functions.php
 * 
 * @since 1.0.0
 */ 
add_action( 'evolution_before_title', 'evolution_category', 5);


/**
 * Show meta tags for posts
 * 
 * @see evolution_entry_meta()
 * @see inc/frontend/evolution-frontend-functions.php
 * 
 * @since 1.0.0
 */ 
add_action( 'evolution_after_title', 'evolution_entry_meta', 5);



/**
 * Show content for 404 page
 * 
 * @see evolution_404_content()
 * @see inc/structure/evolution-loop-content.php
 * 
 * @since 1.0.0
 */ 
add_action( 'evolution_do_404', 'evolution_404_content', 15 );
