<?php
/**
* The Evolution Framework
*
* WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
* Please do all modifications in the form of a child theme.
*
* This file handles the content parts loaded inside the loops
*
* @package Evolution Framework\Markup\
* @author  Andreas Hecht
* @license GPL-2.0+
* @link    https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
*/


if ( ! function_exists( 'evolution_full_content' ) ) :
/**
 * Outputs the full content for the index.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_main_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_full_content() {
?>
        <header class="entry-header">
            <?php do_action( 'evolution_before_title' ); ?>
            <?php the_title( sprintf( '<h2 class="entry-title"><a href="%s" rel="bookmark">', esc_url( get_permalink() ) ), '</a></h2>' ); ?>
            <?php do_action( 'evolution_after_title' ); ?>
            <?php if ( has_post_thumbnail() ): ?>
            <?php do_action( 'evolution_before_thumbnail' ); ?>
            <div class="post-thumbnail">
                <?php if ( is_sticky() && is_home() && ! is_paged() ): ?>
                <div class="featured"><?php esc_html_e( 'Featured', 'evolution' ); ?></div>
                <?php endif; ?>
                <figure>
                    <a href="<?php the_permalink(); ?>">
                        <?php the_post_thumbnail( 'evolution' ); ?>
                    </a>
                </figure>
            </div><!-- .post-thumbnail -->
            <?php endif; ?>
            <?php do_action( 'evolution_after_thumbnail' ); ?>
        </header><!-- .entry-header -->
        <div class="entry-content">
            <?php
              /* translators: %s: Name of current post */
              the_content( sprintf(
                  __( 'Continue reading<span class="screen-reader-text"> "%s"</span>', 'evolution' ),
                  get_the_title()
              ) );
              wp_link_pages( array(	'before' => '<div class="page-links">' . esc_html__( 'Pages:', 'evolution' ), 'after'  => '</div>', 'pagelink' => '<span class="page-numbers">%</span>',  ) );
            ?>
        </div><!-- .entry-content -->   
<?php }
endif;




if ( ! function_exists( 'evolution_summary_content' ) ) :
/**
 * Outputs the excerpt content for index.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_main_loop'
 * 'evolution_do_search_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_summary_content() {
?>
        <header class="entry-header">
            <?php do_action( 'evolution_before_title' ); ?>
            <h2 class="entry-title"><a href="<?php the_permalink(); ?>" rel="bookmark"><?php the_title(); ?></a></h2>
            <?php do_action( 'evolution_after_title' ); ?>
            <?php if ( has_post_thumbnail() ): ?>
            <div class="post-thumbnail">
                <?php do_action( 'evolution_before_thumbnail' ); ?>
                <?php if ( is_sticky() && is_home() && ! is_paged() ): ?>
                <div class="featured"><?php esc_html_e( 'Featured', 'evolution' ); ?></div>
                <?php endif; ?>
                <figure>
                <a href="<?php the_permalink(); ?>">
                <?php the_post_thumbnail( 'evolution' ); ?>
                </a>
                </figure>
            </div><!-- .post-thumbnail -->
            <?php endif; ?>
            <?php do_action( 'evolution_after_thumbnail' ); ?>
        </header><!-- .entry-header -->
        <div class="entry-summary">
            <?php the_excerpt(); ?>
        </div><!-- .entry-summary -->    
<?php }
endif;




if ( ! function_exists( 'evolution_content_none' ) ) :
/**
 * Outputs the no content found content
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_main_loop'
 * 'evolution_do_single_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_content_none() {
?>
<section class="no-results not-found">
    <header class="page-header">
        <h1 class="page-title"><?php esc_html_e( 'Nothing Found', 'evolution' ); ?></h1>
    </header><!-- .page-header -->
    
    <div class="page-content">
        <?php if ( is_home() && current_user_can( 'publish_posts' ) ) : ?>

        <p><?php printf( wp_kses( __( 'Ready to publish your first post? <a href="%1$s">Get started here</a>.', 'evolution' ), array( 'a' => array( 'href' => array() ) ) ), esc_url( admin_url( 'post-new.php' ) ) ); ?></p>

        <?php elseif ( is_search() ) : ?>

        <p><?php esc_html_e( 'Sorry, but nothing matched your search terms. Please try again with some different keywords.', 'evolution' ); ?></p>
        <?php get_search_form(); ?>

        <?php else : ?>

        <p><?php esc_html_e( 'It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching can help.', 'evolution' ); ?></p>
        <?php get_search_form(); ?>

        <?php endif; ?>
    </div><!-- .page-content -->
</section><!-- .no-results -->    
<?php }
endif;




if ( ! function_exists( 'evolution_single_content' ) ) :
/**
 * Outputs the excerpt content
 * 
 *@hooked into the `evolution_do_single` action in the search.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_single_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_single_content() {
?>
<div class="post-full post-full-summary">
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
        <header class="entry-header">
            <?php do_action( 'evolution_before_title' ); ?>
            <h1 class="entry-title"><?php the_title(); ?></h1>
            <?php do_action( 'evolution_after_title' ); ?>
            <?php if ( has_post_format( 'video' ) ) : ?>
            <?php else : ?>
            <div class="post-thumbnail">
                <figure>
                    <?php the_post_thumbnail( 'evolution' ); ?>
                </figure>
            </div>
            <?php endif; ?>
            <?php do_action( 'evolution_after_thumbnail' ); ?>			
        </header><!-- .entry-header -->
        <div class="entry-content">
            <?php the_content(); ?>
            <?php wp_link_pages( array(	'before' => '<div class="page-links">' . esc_html__( 'Pages:', 'evolution' ), 'after'  => '</div>', 'pagelink' => '<span class="page-numbers">%</span>',  ) ); ?>
        </div><!-- .entry-content -->
        <?php if ( get_the_tags() ) : ?>
        <div class="tags-links">
            Tags: <?php the_tags( '', esc_html__( ', ', 'evolution' ) ); ?>
        </div>
        <?php endif; // End if $the_tags ?>
        <?php do_action( 'evolution_after_content' ); ?>
    </article><!-- #post-## -->
</div><!-- .post-full -->
<?php evolution_post_nav(); ?>
<?php if ( class_exists( 'Jetpack_RelatedPosts' ) ) : ?>
<?php echo do_shortcode( '[jetpack-related-posts]' ); ?>
<?php endif; ?>    
<?php }
endif;




if ( ! function_exists( 'evolution_page_content' ) ) :
/**
 * Outputs the page content
 * 
 *@hooked into the `evolution_do_page` action in the search.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_page_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_page_content() {
?>
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
    <?php if( ! get_post_meta( get_the_ID(), 'evolution_hide_page_title', true ) ) : ?>
    <header class="entry-header">
        <?php if( is_front_page() ) : ?>
        <h2 class="entry-title"><?php the_title(); ?></h2>
        <?php else : ?>
        <h1 class="entry-title"><?php the_title(); ?></h1>
        <?php endif; ?>
    </header><!-- .entry-header -->
    <?php endif; ?>
    <div class="entry-content">
        <?php the_content(); ?>
        <?php wp_link_pages( array(	'before' => '<div class="page-links">' . esc_html__( 'Pages:', 'evolution' ), 'after'  => '</div>', 'pagelink' => '<span class="page-numbers">%</span>',  ) ); ?>
    </div><!-- .entry-content -->
</article><!-- #post-## -->    
<?php }
endif;


if ( ! function_exists( 'evolution_list_content' ) ) :
/**
 * Outputs the page content
 * 
 *@hooked into the `evolution_do_search` action in the search.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_search_loop'
 * 
 * @see /inc/structure/evolution-loops.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_list_content() {
?>
<div class="post-list post-grid-list">
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
        <?php if ( has_post_thumbnail() ): ?>
        <div class="post-thumbnail">
            <a href="<?php the_permalink(); ?>">
            <?php the_post_thumbnail( 'evolution-post-thumbnail-medium' ); ?>
            </a>
        </div><!-- .post-thumbnail -->
        <?php else : ?>
        <div class="post-thumbnail">
        <a href="<?php the_permalink(); ?>">
            <img id="placeholder" src="<?php echo get_template_directory_uri(); ?>/images/placeholder-small.png" alt="placeholder" width="260" height="260" />
            </a>
        </div><!-- .post-thumbnail -->
        <?php endif; ?>
        <div class="post-list-content">
            <header class="entry-header">
                <?php if ( is_sticky() && is_home() && ! is_paged() ): ?>
                <div class="featured"><?php esc_html_e( 'Featured', 'evolution' ); ?></div>
                <?php endif; ?>
                <h2 class="entry-title"><a href="<?php the_permalink(); ?>" rel="bookmark"><?php the_title(); ?></a></h2>
                <?php evolution_entry_meta(); ?>
            </header><!-- .entry-header -->
            <div class="entry-summary">
                <?php the_excerpt(); ?>
            </div><!-- .entry-summary -->
        </div><!-- .post-list-content -->
    </article><!-- #post-## -->
</div><!-- .post-list -->    
<?php }
endif;




if ( ! function_exists( 'evolution_404_content' ) ) :
/**
 * Outputs the 404 content
 * 
 *@hooked into the `evolution_do_search` action in the search.php
 * 
 * The action hooks called are:
 * 
 * 'evolution_do_404'
 * 
 * @see 404.php
 *
 * @since  1.0.0
 * @return  void
 */
function evolution_404_content() {
?>
<section class="error-404 not-found">
    <header class="page-header">
        <h1 class="page-title">
            <?php esc_html_e( '404 - That page can&rsquo;t be found.', 'evolution' ); ?>
        </h1>
    </header><!-- .page-header -->

    <div class="page-content">
        <p>
            <?php esc_html_e( 'It looks like nothing was found at this location. Maybe try a search?', 'evolution' ); ?>
        </p>

        <aside class="widget widget_search">
            <?php get_search_form(); ?>
        </aside>

    </div><!-- .page-content -->
</section><!-- .error-404 -->    
<?php }
endif;
